### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/laravel-starter#1]
## Situation

At this point we will have an empty project, ready to get feed with some data. So lets begin to tackle down the default structure and prepare everything in order to get ready for development.

## Tasks

- [x] Provide common project files.
- [x] Install a fresh Laravel skeleton application (v.5.3).
- [x] Add and install additional packages and extensions.
- [x] Refactor assets workflow and resources.
- [x] Refactor default testing and add Travis CI for testing.
- [x] Refactor complete application in order to confirm the coding standards.
- [x] Provide a layout page (master), which will be used within the application.
- [x] Add a 404 and refactor other views.

**Comment by sirthxalot** [comment]
## Additional Packages

- [x] [Anchor JS](https://www.npmjs.com/package/anchor-js)
- [x] [AOS](https://www.npmjs.com/package/aos)
- [x] [Chart JS](https://www.npmjs.com/package/chart.js)
- [x] [Clipboard](https://www.npmjs.com/package/clipboard)
- [x] [Font Awesome](https://www.npmjs.com/package/font-awesome)
- [x] [Foundation for Sites](https://www.npmjs.com/package/foundation-sites)
- [x] [jQuery](https://www.npmjs.com/package/jquery)
- [x] [Motion UI](https://www.npmjs.com/package/motion-ui)
- [x] [Retina JS](https://www.npmjs.com/package/retinajs)
- [x] [Tiny MCE](https://www.npmjs.com/package/tinymce)
- [x] [Vue JS](https://www.npmjs.com/package/vue)
- [x] [Vue Ressource](https://www.npmjs.com/package/vue-resource)
- [x] [What Input](https://www.npmjs.com/package/what-input)

**Development Only**:

- [x] [Gulp](https://www.npmjs.com/package/gulp)
- [x] [Laravel Elixir](https://www.npmjs.com/package/laravel-elixir)
- [x] [Laravel Elixir Vue](https://www.npmjs.com/package/laravel-elixir-vue)
- [x] [Laravel Elixir Webpack](https://www.npmjs.com/package/laravel-elixir-webpack-official)
- [x] [Lodash](https://www.npmjs.com/package/lodash)

**Comment by sirthxalot** [comment]
## Additonal Extensions

- [x] [Agent](http://packalyst.com/packages/package/jenssegers/agent)
- [x] [Debugbar](http://packalyst.com/packages/package/barryvdh/laravel-debugbar)
- [x] [Excel](http://packalyst.com/packages/package/maatwebsite/excel)
- [x] [Intervention Image](http://packalyst.com/packages/package/intervention/image)

**Development Only**:

- [x] [Generators](https://github.com/laracasts/Laravel-5-Generators-Extended)
- [x] [IDE-Helper](https://github.com/barryvdh/laravel-ide-helper)
- [x] [Test Dummy](https://github.com/laracasts/TestDummy)
