### ISSUE TITLE
Initial commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/laravel-starter#1]
At this point I will have an empty project, ready to get feed with some data. So let's begin to tackle down the default structure and add some common files.

**Comment by sirthxalot** [comment]
## Tasks

- [ ] Install fresh Laravel skeleton application (above v.5.4), using Laravel installer.
- [ ] Move generated project files into root directory of project.
- [ ] Add common project files, e.g. `readme.md`, `license.md` ...

*v.0.1.1-0001*
