### ISSUE TITLE
Add Bulma CSS framework.

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/laravel-starter#2]
> As **a developer**, I **would like** to have a starting point for designing the application.

**Comment by sirthxalot** [comment]
## Tasks

- [ ] Add Bulma CSS to Composer dependencies and install it.
- [ ] Integrate Bulma into the SASS workflow and generate the assets for it.
- [ ] Add Font-Awesome using CDN link to the common CSS file.
