### ISSUE TITLE
Add Laravel Debugbar.

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/laravel-starter#5]
## Tasks

- [x] Add Laravel-Debugbar to Composer dependencies.
- [x] Implement Laravel-Debugbar into the application.
- [x] Publish the vendor configuration for the Laravel-Debugbar.
